CREATE TABLE [dbo].[Contacts]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
	[FirstName] NVARCHAR(255) NOT NULL DEFAULT '', 
    [LastName] NVARCHAR(255) NOT NULL DEFAULT '',
	[Phone] NVARCHAR(255) NOT NULL DEFAULT '',
	[Email] NVARCHAR(255) NOT NULL DEFAULT '',
	[Street] NVARCHAR(255) NOT NULL DEFAULT '',
	[City] NVARCHAR(255) NOT NULL DEFAULT '', 
	[State] NVARCHAR(100) NOT NULL DEFAULT '',
	[Zip] NVARCHAR(50) NOT NULL DEFAULT '',
	[Description] NVARCHAR(255) NOT NULL DEFAULT ''
	)
