CREATE TABLE [dbo].[Contacts]
(
	[ID] INT NOT NULL IDENTITY(1,1) PRIMARY KEY,
    [UserID] INT references Users(ID) NOT NULL,
	[FirstName] NVARCHAR(255) NOT NULL DEFAULT '', 
    [LastName] NVARCHAR(255) NOT NULL DEFAULT '', 
    [Email] NVARCHAR(255) NOT NULL DEFAULT '',
    [PhoneNumber] NVARCHAR(255) NOT NULL DEFAULT '',
    [Address] NVARCHAR(255) NOT NULL DEFAULT '', 
    [City] NVARCHAR(255) NOT NULL DEFAULT '', 
    [State] NVARCHAR(255) NOT NULL DEFAULT '', 
    [Zip] NVARCHAR(255) NOT NULL DEFAULT ''
)
